version: "3.9"

services:
  tba-nginx:
    image: 'nginx:stable-alpine'
    container_name: tba-nginx
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  tba-mysql:
    image: mysql:5.7
    user: "${UID}:${GID}"
    container_name: tba-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./docker-configs/sys/:/var/lib/mysql/
  phpmyadmin:
    depends_on:
      - tba-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      PMA_HOST: tba-mysql
      MYSQL_ROOT_PASSWORD: root
  tba-app:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: tba-app
    volumes:
      - ./:/var/www/html
  tba-mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025 # smtp server
      - 8003:8025 # web ui
